[package]
name = "subprocess"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "subprocess"
crate-type = ["cdylib"]

[dependencies]
libc = "0.2.171"
rustler = { version = "0.36.1", features = ["serde"] }
serde = { version = "1.0.219", features = ["derive"] }
