name: "Run tests"

on:
  push:
  pull_request:
    types: ["synchronize"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v4
    - name: Install Lix
      uses: canidae-solutions/lix-quick-install-action@v2
    - name: Build and test memorable
      run: nix build -L -f default.nix memorable
